package com.wanggh8.mydrive.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wanggh8.mydrive.bean.DriveBean;

import com.wanggh8.mydrive.db.DriveBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig driveBeanDaoConfig;

    private final DriveBeanDao driveBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        driveBeanDaoConfig = daoConfigMap.get(DriveBeanDao.class).clone();
        driveBeanDaoConfig.initIdentityScope(type);

        driveBeanDao = new DriveBeanDao(driveBeanDaoConfig, this);

        registerDao(DriveBean.class, driveBeanDao);
    }
    
    public void clear() {
        driveBeanDaoConfig.clearIdentityScope();
    }

    public DriveBeanDao getDriveBeanDao() {
        return driveBeanDao;
    }

}
